version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - type: bind
        source: ./storage/postgres
        target: /var/lib/postgresql/data
    networks:
      - net-keycloak

  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:22.0
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - 9090:8080
    # https://www.keycloak.org/server/configuration
    #command: 
    # - start --help
    # - start --optimized 
    command:
      - start-dev
    networks:
      - net-keycloak

networks:
  net-keycloak:
